name: Deploy Surge Website
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install --location=global surge
    - run: npm run build
    - run: surge --project ./dist --domain https://vite-jobfair-comingsoon.surge.sh --token ${{ secrets.SURGE_TOKEN }}